Supprimer un pays
<p>Etes-vous sur de vouloir supprimer le pays :
<?php
echo $this->escape($this->pays['nom'])."(id = ".$this->pays['id'].")";
?>
<form action="<?php echo $this->url(array('controller'=>'pays','action'=>'supprimer')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->pays['id']; ?>">
        <input type="submit" name="supprimer" value="Oui">
        <input type="submit" name="supprimer" value="Non">
    </div>
</form>